title: Andrew Redston # your name (or website title) here
logo: "images/aredston.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Is this thing working. 
  <br><br>
  Test 1 Test 2  
  <br><br>
  <a href="https://www.linkedin.com/in/aredston//">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
